### PR TITLE
Remove dependency on jsonld.js

### PR DESCRIPTION
**Pull request by rubensworks**
This uses streaming JSON-LD processing whenever possible, using:

* https://www.npmjs.com/package/jsonld-streaming-parser (in `JsonLdDatasource`)
* https://www.npmjs.com/package/jsonld-streaming-serializer (in `RdfView#_createJsonLdWriter`)

### CODE REVIEW

**Comment by rubensworks** [comment]
Fails on Node 6 because these libs require Node >= 8, is this a blocker @RubenVerborgh?

**Comment by RubenVerborgh** [comment]
10 is already LTS now, so 8 more than fine.

**Comment by rubensworks** [comment]
^ Removed support for Node 6 and added Node 10 to the Travis matrix.

**Comment by mielvds** [comment]
Can we merge this one?

**Comment by rubensworks** [comment]
Obsoleted by b014f67c55550260dc3f0032594c759bf570e983

**Pull request closed without merging**
