### PR TITLE
Use node-slim for smaller image

### PR DESCRIPTION
**Pull request by barthanssens**
Down to about 280 MB instead of 700+

g++ and make are added (and removed) to build the optional HDT support

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Thanks, nice touch with the removal of g++ and make :wink:

**Comment by barthanssens** [comment]
You're welcome :-)

It's weird though that the Travis CI build failed. I'm running the node-slim version on http://server.fragments.belgif.be with one HDT dataset, and that seems to work just fine...
Maybe I'm missing something here ?

**Comment by thadguidry** [comment]
@barthanssens why is there a dash character ?  `$ export CXX=g++-4.8`

**Comment by barthanssens** [comment]
@thadguidry uhm, no idea... that's part of the travis config I guess ...

**Comment by thadguidry** [comment]
@barthanssens Ah, its a 'make' thing.
CMAKE_C_COMPILER 
the compiler used for C files. Normally it is detected and set during the CMake run, but you can override it at configuration time. Note! It can not be changed after the first cmake or ccmake run. Although the gui allows to enter an alternative, it will be ignored in the next 'configure' run. Use for example: 
CC=gcc-3.3 CXX=g++-3.3 cmake
to set the compiler. (You can also set CMAKE_C_COMPILER_INIT, before any PROJECT() or ENABLE_LANGUAGE() command.) Any other way (like writing make CC=gcc-3.3 CXX=g++-3.3) will not work. When using distcc or similar tools, you need to write: 
CC="distcc gcc-3.3" CXX="distcc g++-3.3" cmake
However, this will empty all your CMAKE_..._FLAGS_... above.

**Comment by barthanssens** [comment]
Thank you for the detailed analysis. So if I understand it correctly it has to be changed on the Travis side (I don't have access to this build environment)
Or is it an issue I can fix in Docker (by unsetting all environment flags that may trickle down into the docker image, before the RUN ?). Thanks

**Comment by thadguidry** [comment]
@barthanssens no idea Bart.  Even I would have to dig in as well.  Sorry, can't help more, but the Travis logs themselves show the issues.  Just click that [Details](https://travis-ci.org/LinkedDataFragments/Server.js/builds/289914973?utm_source=github_status&utm_medium=notification) link above and then click on one of the individual build jobs to see the nitty gritty details.  Looks like some filepath issues also ?

```
1) LinkedDataFragmentsServer Uncaught error outside test suite:
     Uncaught Error: Could not open HDT file "/home/travis/build/LinkedDataFragments/Server.js/test/assets/test.hdt"
      at Error (native)
      at node_modules/hdt/lib/hdt.js:60:38
```
 or perhaps that's because something was missing much higher up in the logs like this I see ...

```
Index generated in 99 us
  LinkedDataFragmentsServer
    1) Uncaught error outside test suite
```

**Comment by rubensworks** [comment]
Don't worry about the failing Travis build, this is due to a change in the HDT-Node dependency, which has been resolved on the `develop` branch thanks to 8978a3b022bcaace8db3772141ec00f267c18fc9.

**Comment by rubensworks** [comment]
Thanks for the PR @barthanssens!

**Pull request merged**
