### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by barthanssens**
Use latest Node.js v4

### CODE REVIEW

**Comment by rubensworks** [comment]
I agree that the latest Node version should be used in the Dockerfile, I don't think setting a 4.x.x version range is a good idea as it adds non-determinism to the builds.

With this it could be that a docker build at one point in time will fail to build, while at a later point it will succeed, because it could be using a different/newer Node version.

I can look into upgrading to the latest Node base image if that helps, but I'd rather not merge this  because I tend to avoid dynamic versions as much as possible.

@RubenVerborgh What's your opinion? I know NPM uses dynamic versions extensively, which is not always a good thing as we have noticed.

**Comment by RubenVerborgh** [comment]
Well, if a Docker image breaks, it's a sign that something's really wrong with our code. Breakages within a major Node version should not occur.

**Comment by rubensworks** [comment]
> Well, if a Docker image breaks, it's a sign that something's really wrong with our code.

That's the thing, we won't be able to detect it unless we try rebuilding the image _every time_ a new Node version is released. With a fixed version there's no chance at all that it will break if it worked at one point.

Furthermore, detecting for what Node version it broke might not always be trivial to figure out, because Docker doesn't have a concept of lock files AFAIK.

**Comment by RubenVerborgh** [comment]
It's the same with our CI in a sense; always runs on the latest Node. I don't mind myself, but it's your call.

**Comment by rubensworks** [comment]
Closing this in favor of 1716b60964e9d92a20f9068d98cc71c52c9ad9be, for ensuring reproducible builds.

We will further update the Node Docker base image version when needed.

**Pull request closed without merging**
