### PR TITLE
Support quads in SparqlDatasource

### PR DESCRIPTION
**Pull request by rubensworks**
This allows quad pattern SPARQL queries to be constructed for communicating with SPARQL endpoints.
Responses in TriG format are preferred.

Can be tested with the following endpoint: https://stad.gent/sparql

http://dbpedia.restdesc.org/ doesn't seem to return TriG responses, so that one will fall back to placing all triples in the default graph.

The `defaultGraph` config field for SparqlDatasources has been removed because it is not required anymore to make a graph selection at config-level anymore, QPF simply returns everything in all graphs.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Instead of TriG, which might not be widely supported, should we consider SELECT queries and parse CSV or JSON?

**Comment by rubensworks** [comment]
I tried to stay in the RDF-realm as much as possible, but sure, I can do that :-)

**Comment by RubenVerborgh** [comment]
Yeah, sorry about this, I just realized it now. In hindsight, a `SELECT` should have been what I did in the first place, given the current ugly code with first trying Turtle and falling back to N-Triples.

I wonder whether CSV or JSON is best. On the one hand, CSV has lowest overhead (the JSON has a lot of boilerplate), but the CSV might have encoding problems (what if there are delimiters in the strings). So it all depends on whether SPARQL strictly defines the CSV variant, and whether all implementations follow this.

**Comment by rubensworks** [comment]
I am currently implementing the JSON approach because it looked a lot easier to parse and decode.

The downside is that it can't be streamed anymore, which would be possible with CSV, but as each request will have a low LIMIT anyways, this shouldn't be an problem.

**Comment by RubenVerborgh** [comment]
Yeah, I'm not worried about streaming. Overhead of streaming parser might actually be more than just parsing everything at once.

**Comment by rubensworks** [comment]
Query results are now requested as `application/sparql-results+json`, which for Virtuoso endpoints results in much more robust interfacing.

Furthermore, 9a5773882dff1829a224f071824e1ba783b5dad8 solves the issue that slow counts are triggered again for each next page for the same quad pattern. Only the request of the first page might be slow, the next ones are guaranteed to be fast.

**Comment by RubenVerborgh** [comment]
Great work, @rubensworks, thanks a lot!

**Comment by RubenVerborgh** [comment]
Temporary public demo available at http://data-beta.linkeddatafragments.org/.

**Pull request merged**
