### PR TITLE
Deal with SPARQL endpoint COUNT timeouts gracefully

### PR DESCRIPTION
**Pull request by RubenVerborgh**
The server did this before 7a7c121983eabc047181d931d2908e2b30108c03.

### CODE REVIEW

**Comment by mielvds** [comment]
So default to 1e9?

**Comment by rubensworks** [comment]
Looks good to me!
Tested, and everything seems to work fine.

For better configurability, it might be nice in the future if the max timeout and fallback total count values can be changed.

**Comment by RubenVerborgh** [comment]
@mielvds Yes.

@rubensworks Agree on configurability; however, we probably better merge `feature-lsd` first to avoid conflicts.

**Comment by RubenVerborgh** [comment]
Changed the execution slightly: now the default value of 1,000,000,000 will be returned after three seconds; however, the server waits for 10 seconds to still receive a correct count from the SPARQL endpoint, which might then be cached for future use.

I also rebased this on `feature-qpf-latest`, so I suggest that @rubensworks merges this PR before adding quad support to the SPARQL endpoint datasource in that branch.

**Comment by udp** [comment]
> I also rebased this on feature-qpf-latest, so I suggest that @rubensworks merges this PR before adding quad support to the SPARQL endpoint datasource in that branch.
 
Great, now a) we can't get the fix without rebasing it back onto develop, and b) it no longer has a feature branch, so I'll have to cherry pick the commits.

**Pull request merged**
